name: openGL Test

on:
  # main branch PR 시 실행
  # pull_request:
  #     branches:
  #       - main
    
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: write
      id-token: write 

    steps:
    # 1. 저장소 코드 체크아웃
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Create a folder and compress it into a ZIP
      shell: cmd
      run: |
        mkdir myfolder
        echo "This is file 1" > myfolder/file1.txt
        echo "This is file 2" > myfolder/file2.txt

    - name: Compress files into a ZIP
      shell: powershell
      run: |
        Compress-Archive -Path myfolder\* -DestinationPath uivat.zip

    - name: Verify ZIP file
      shell: bash
      run: |
        ls -lh uivat.zip
        unzip -l uivat.zip
    
    # 2. Bump version and push the tag
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
          
    # 7. Github release 생성
    - name: Create GitHub release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body:  |
          ## What's Changed
          ${{ steps.tag_version.outputs.changelog }}
          ---
          ${{ steps.tag_version.outputs.changelog }}
    
    # 8. 빌드 결과 업로드
    - name: Upload release assets
      id: upload-release-assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./uivat.zip
        asset_name: uivat.zip
        tag: ${{ steps.tag_version.outputs.new_tag }}
        overwrite: true

    - name: Create GitHub release in dist repo
      id: create_release_dist_repo
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: uivat_${{ steps.tag_version.outputs.new_tag }}
        body: |
          ## What's Changed
          ${{ steps.tag_version.outputs.changelog }}
        repo: dist_repository
        token: ${{ secrets.ACTIONS_PAT }}
    
    - name: Upload release assets to dist repo
      id: upload_release_assets_dist_repo
      uses: svenstaro/upload-release-action@v2
      with:
        repo_name: jungsu0717/dist_repository
        repo_token: ${{ secrets.ACTIONS_PAT }}
        file: ./uivat.zip
        asset_name: uivat.zip
        tag: ${{ steps.tag_version.outputs.new_tag }}
