name: openGL Test

on:
  # main branch PR 시 실행
  # pull_request:
  #     branches:
  #       - main

  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: write
      id-token: write 

    steps:
    # 1. 저장소 코드 체크아웃
    - name: Checkout
      uses: actions/checkout@v4.2.2

    # Miniconda 설치 및 uivat 환경 구축
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        activate-environment: uivat
        python-version: 3.12.4
     
    # Conda 설치 확인
    - name: PowerShell
      shell: powershell
      run: |
        conda info
        conda list
        conda --version
        conda env list

    - name: Create a folder and compress it into a ZIP
      shell: cmd
      run: |
        conda list
        mkdir myfolder
        echo "This is file 1" > myfolder/file1.txt
        echo "This is file 2" > myfolder/file2.txt

    - name: Compress files into a ZIP
      shell: powershell
      run: |
        conda list
        ls
        cd
        dir
        Compress-Archive -Path myfolder\* -DestinationPath uivat.zip

    - name: Verify ZIP file
      shell: bash
      run: |
        conda list
        ls -lh uivat.zip
        unzip -l uivat.zip
    
    # 2. Bump version and push the tag
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # body:  |
    # ## What's Changed
    # ${{ steps.tag_version.outputs.changelog }}
    # ---
    # ${{ steps.tag_version.outputs.changelog }}
    # 7. Github release 생성
    - name: Create GitHub release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: uivat_${{ steps.tag_version.outputs.new_tag }}
        artifacts: "uivat.zip"
        generateReleaseNotes: true
   
    - name: Create GitHub release in dist repo
      id: create_release_dist_repo
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: uivat_${{ steps.tag_version.outputs.new_tag }}
        artifacts: "uivat.zip"
        generateReleaseNotes: true
        repo: dist_repository
        token: ${{ secrets.ACTIONS_PAT }}     
    
    # # 8. 빌드 결과 업로드
    # - name: Upload release assets
    #   id: upload-release-assets
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: ./uivat.zip
    #     asset_name: uivat.zip
    #     tag: ${{ steps.tag_version.outputs.new_tag }}
    #     overwrite: true
    #     release_name: Test v${{ steps.tag_version.outputs.new_tag }}
    #     body: |
    #       ## What's Changed
    #       ${{ steps.tag_version.outputs.changelog }}
    #       ---
    #       ${{ steps.tag_version.outputs.changelog }}


    
    # - name: Upload release assets to dist repo
    #   id: upload_release_assets_dist_repo
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_name: jungsu0717/dist_repository
    #     repo_token: ${{ secrets.ACTIONS_PAT }}
    #     file: ./uivat.zip
    #     asset_name: uivat.zip
    #     tag: ${{ steps.tag_version.outputs.new_tag }}
