name: openGL Test

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
    # 1. 저장소 코드 체크아웃
    - name: Checkout
      uses: actions/checkout@v4.2.2

    # - name: Install Mesa
    #   shell: cmd
    #   run: |
    #     curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/20.3.2/mesa3d-20.3.2-release-msvc.7z
    #     "C:\Program Files\7-Zip\7z.exe" x mesa.7z
    #     mklink opengl32.dll "x64\opengl32.dll"
    #     mklink libglapi.dll "x64\libglapi.dll"

    # - name: Overwrite OpenGL DLLs in x64
    #   run: |
    #     copy /y x64\opengl32.dll opengl32.dll
    #     copy /y x64\libglapi.dll libglapi.dll

    # - name: Check Current Directory
    #   run: dir x64
    #   shell: cmd

    - name: Check Current Directory2
      run: dir
      shell: cmd
        
    # 3. Kivy GL Backend 설정
    - name: Set Kivy GL Backend
      run: set KIVY_GL_BACKEND=angle_sdl2

    # 4. Python 환경 설정
    - name: Setup Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.12.4

    # 5. pyopengl과 pygame 설치
    - name: Install pyopengl and pygame
      run: |
        pip install pyopengl pygame

    # 6. OpenGL 버전 확인
    - name: Check OpenGL Version with Pygame
      run: |
        python -c "import pygame; pygame.init(); display = pygame.display.set_mode((1, 1), pygame.OPENGL); from OpenGL.GL import glGetString, GL_VERSION; print('OpenGL Version:', glGetString(GL_VERSION).decode())"
